{
  "modified": "2024-06-25T13:32:17Z",
  "published": "2024-06-25T13:32:17Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-4752",
  "summary": "Malicious code in ailzyn1tr0 (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "ailzyn1tr0",
        "purl": "pkg:pypi/ailzyn1tr0"
      },
      "versions": [
        "1.0"
      ]
    }
  ],
  "references": [
    {
      "type": "WEB",
      "url": "https://github.com/DataDog/malicious-software-packages-dataset"
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "id": "RLMA-2024-03532",
        "import_time": "2024-06-28T02:48:14.414533643Z",
        "modified_time": "2024-06-25T13:32:17Z",
        "sha256": "eec39cb13b5ff9189983c87d108eb1a4191b0ce516787834e816e254601a38e0",
        "source": "reversing-labs",
        "versions": [
          "1.0"
        ]
      }
    ]
  }
}
