{
  "modified": "2024-06-25T13:37:51Z",
  "published": "2024-06-25T13:37:51Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-5441",
  "summary": "Malicious code in p8llow (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "p8llow",
        "purl": "pkg:pypi/p8llow"
      },
      "versions": [
        "1.0.0"
      ]
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "id": "RLMA-2024-04223",
        "import_time": "2024-06-28T02:49:35.034672685Z",
        "modified_time": "2024-06-25T13:37:51Z",
        "sha256": "d041c02d616391fba699601ea16251f6df2b218b6ae4c54afdd44d6ca1c3ddea",
        "source": "reversing-labs",
        "versions": [
          "1.0.0"
        ]
      }
    ]
  }
}
