{
  "modified": "2024-06-25T13:35:26Z",
  "published": "2024-06-25T13:35:26Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-5143",
  "summary": "Malicious code in flaks-setup (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "flaks-setup",
        "purl": "pkg:pypi/flaks-setup"
      },
      "versions": [
        "0.93",
        "0.95",
        "0.1",
        "0.9",
        "0.7",
        "0.94",
        "1.1",
        "0.3",
        "1.0",
        "0.5",
        "0.91",
        "0.92",
        "0.6",
        "0.2",
        "1.2",
        "0.8"
      ]
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "id": "RLMA-2024-03923",
        "import_time": "2024-06-28T02:48:59.22529514Z",
        "modified_time": "2024-06-25T13:35:26Z",
        "sha256": "4e91b73e49cb05e6d45e9a2624589b4a357aba0335067b46266a0023c4ca7f06",
        "source": "reversing-labs",
        "versions": [
          "0.93",
          "0.95",
          "0.1",
          "0.9",
          "0.7",
          "0.94",
          "1.1",
          "0.3",
          "1.0",
          "0.5",
          "0.91",
          "0.92",
          "0.6",
          "0.2",
          "1.2",
          "0.8"
        ]
      }
    ]
  }
}
