{
  "modified": "2024-06-25T13:37:10Z",
  "published": "2024-06-25T13:37:10Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-5354",
  "summary": "Malicious code in mayalbl (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "mayalbl",
        "purl": "pkg:pypi/mayalbl"
      },
      "versions": [
        "5"
      ]
    }
  ],
  "references": [
    {
      "type": "WEB",
      "url": "https://github.com/DataDog/malicious-software-packages-dataset"
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "id": "RLMA-2024-04136",
        "import_time": "2024-06-28T02:49:24.993972522Z",
        "modified_time": "2024-06-25T13:37:10Z",
        "sha256": "03273065951e8ead69d288e2ec29e503c8b3c9edde8e10757bf9f2bc8677e3d6",
        "source": "reversing-labs",
        "versions": [
          "5"
        ]
      }
    ]
  }
}
