{
  "modified": "2024-06-25T13:41:46Z",
  "published": "2024-06-25T13:41:46Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-5908",
  "summary": "Malicious code in requesttest3 (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "requesttest3",
        "purl": "pkg:pypi/requesttest3"
      },
      "versions": [
        "1.0.1",
        "1.0.2"
      ]
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "id": "RLMA-2024-04709",
        "import_time": "2024-06-28T02:50:32.547652904Z",
        "modified_time": "2024-06-25T13:41:46Z",
        "sha256": "45fd3dbd5757dfedd23e335857d4a95478ab665792c7f6a87e454c85837b3954",
        "source": "reversing-labs",
        "versions": [
          "1.0.1",
          "1.0.2"
        ]
      }
    ]
  }
}
