{
  "modified": "2024-06-25T13:38:26Z",
  "published": "2024-06-25T13:38:26Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-5513",
  "aliases": [
    "SNYK-PYTHON-PIPCRYPTOADDONV1-5932170"
  ],
  "summary": "Malicious code in pipcryptoaddonv1 (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "pipcryptoaddonv1",
        "purl": "pkg:pypi/pipcryptoaddonv1"
      },
      "versions": [
        "1.1.0",
        "1.0.0"
      ]
    }
  ],
  "references": [
    {
      "type": "ARTICLE",
      "url": "https://medium.com/checkmarx-security/the-evolutionary-tale-of-a-persistent-python-threat-d19196d4ed15"
    },
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-PIPCRYPTOADDONV1-5932170"
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "id": "RLMA-2024-04295",
        "import_time": "2024-06-28T02:49:43.444649009Z",
        "modified_time": "2024-06-25T13:38:26Z",
        "sha256": "1012d3eea4251b70d4b2cc683037aed7c672cb89ec202cd96e0ed483901f523b",
        "source": "reversing-labs",
        "versions": [
          "1.1.0",
          "1.0.0"
        ]
      }
    ]
  }
}
