{
  "modified": "2024-06-25T13:38:12Z",
  "published": "2024-06-25T13:38:12Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-5484",
  "summary": "Malicious code in pip-remote-access-test (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "pip-remote-access-test",
        "purl": "pkg:pypi/pip-remote-access-test"
      },
      "versions": [
        "0.0.3"
      ]
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "id": "RLMA-2024-04266",
        "import_time": "2024-06-28T02:49:39.835542224Z",
        "modified_time": "2024-06-25T13:38:12Z",
        "sha256": "1132cb5dff1a9c741dce0f66ed6ba1ce8fea02eb88a9d37f297d3d069ee9b8d0",
        "source": "reversing-labs",
        "versions": [
          "0.0.3"
        ]
      }
    ]
  }
}
